### ISSUE TITLE
Question: How does one use other providers on 'pages'

### ISSUE THREAD

**Issue by gyoza** [JVMartin/angel-core#3]
I am trying to use former and it does not appear to be working... I assumed that you would be putting the laravel code in the "modules" section but it does not appear to be working..

Also, just out of curiosity, why are all the pages stored in the database? Thanks, so far I think this project is wonderful!

Best Regards,
Gyoza.

**Comment by JVMartin** [comment]
Hey Gyoza!

This video should help you out:
https://www.youtube.com/watch?v=6iuZ8p-x5bY

In it, I'll show you how to cutomize pages so that you can first publish the views (blades) from the framework and then edit the template or add your own page blades by overriding the PageController.  In those blades, you should be able to use former as normal!

So, you can either create pages in the database from the admin panel, or by overriding the PageController to load your own blades if you want that kind of control and don't need the client to be able to edit it from the admin panel.

I hope this video answers your questions!  Feel free to respond to this thread with any further questions.

**Comment by gyoza** [comment]
Awww yea thanks :) 

Justin A. says hi. He pointed me at this project:) He says you type loud, in the video, it is proven.

**Comment by JVMartin** [comment]
Sure thing!

Oh man haha I wasn't aware of that!  My microphone does sit right on top of my keyboard... :)

**Comment by JVMartin** [comment]
I should clarify one thing I said:  the pages still have to exist in the database for the PageController's show() method to work properly, even if you're going to be using your own view/blade instead of the admin panel's HTML section.  I may change this so that the database rows aren't required in the future.

**Comment by gyoza** [comment]
Hey J,

Ran into an issue with former..
works - 

```
{{Former::checkboxes('checkme')
      ->checkboxes('ffffffffffffffffirst', 'second', 'third', 'fourth')}}
```

Does not work,

```
{{Former::open()->rules(array('name' => 'required|max:20|alpha'))}}
```

 no laravel errors in the laravel log as well. Any ideas?

(FYI, adding a Former::close() at the end causes laravel unexpected ; error)

**Comment by JVMartin** [comment]
I've never used Former before, but I can tell you with 100% confidence that Angel does not extend or modify any of Laravel's classes or other classes in the framework.  It is simply a set of controllers and models, just plain vanilla Laravel usage.  As such, anything that works in Laravel 4.1 will work just fine with Angel.

Perhaps your version of Former isn't compatible with Laravel 4.1?  I may be updating Angel to work with Laravel 4.2 in the very near future, there were some issues with 4.2 still when I began development.

**Comment by Nimoi** [comment]
@Jacob - Do you think Laravel 4.2 is stable enough to upgrade? I haven't
tried it, but I wonder if there would be many issues.

**Comment by JVMartin** [comment]
@Nimoi I'm rewriting one of my applications in 4.2 right now to familiarize myself with all the new traits and differences.  It's far more stable now than it was when I started Angel, so I'll probably be updating Angel to use 4.2 in the next release!  :cake:
